defaults:
  - _self_

dataset: null # specify dataset name without extension

dataset_1_labels:
  - non-conductive
  - conductive

paths:
  data_dir: data
  outputs:  outputs/${dataset}

suffix:
  raw:          .csv
  preprocessed: _preprocessed.csv
  train:        _preprocessed_train.csv
  test:         _preprocessed_test.csv