defaults:
  - _self_

dataset: # specify dataset name without extension

labels:
  - non-conductive
  - conductive

process_data:
  input_path: /data/${dataset}.csv
  output_dir: /data/${dataset}_processed.csv


paths:
  raw:          data/${dataset}.csv
  processed:    data/${dataset}_processed.csv
  train_split:  data/${dataset}_processed_train_data.csv
  test_split:   data/${dataset}_processed_test_data.csv
  outputs:      outputs/${dataset}